[tox]
envlist = lint, tests
skipsdist = True

[testenv]
basepython = python3.14

[testenv:lint]
deps = uv
commands =
    uv run ruff check src tests
    uv run ruff format --check src tests

[testenv:tests]
deps = uv
commands =
    uv run pytest {posargs}
